---
abstract: 'Answer for exercise 21.3 of the book "Intermediate Perl"'
author:
  - 'Junichi Hayashi <j-hayasi@ist.osaka-u.ac.jp>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Acme-NAHCNUJ-Utils
provides:
  Acme::NAHCNUJ::Utils:
    file: lib/Acme/NAHCNUJ/Utils.pm
    version: '0.03'
  Tie::Cycle:
    file: lib/Tie/Cycle.pm
    version: '1.224'
resources:
  license: http://opensource.org/licenses/artistic-license-2.0.php
version: '0.03'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
